set nocompatible " be iMproved
 filetype off " required!
 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()
"插件
 Bundle 'gmarik/vundle'
 Bundle 'AutoComplPop'
 Bundle 'The-NERD-tree'
 Bundle 'Tagbar'
 Bundle 'minibufexpl.vim'
 Bundle 'molokai'
 Bundle 'ZenCoding.vim'
 Bundle 'L9'
 Bundle 'FuzzyFinder'
 Bundle 'WebAPI.vim'
 Bundle 'Gist.vim'
 filetype plugin indent on " required!
"autocomplpop 设置
 let g:AutoComplPop_IgnoreCaseOption=1
 set ignorecase
"搜索高亮
 set hlsearch
"设置NERDTreetagbar的宽度
 let g:NERDTreeWinSize = 20
 let g:tagbar_width=20
"颜色主题设置
 set t_Co=256
 colorscheme molokai
"zencoding 设置
 let g:user_zen_expandabbr_key='&lt;S-O&gt;'
 let g:use_zen_complete_tag = 1
"Gist设置
 let g:gist_detect_filetype = 1
 let g:gist_clip_command = 'xclip -selection clipboard'
"查找手册
 autocmd FileType php set keywordprg=~/.vim/phpman
 autocmd FileType js,css,html set keywordprg=~/.vim/man
"光标设在为竖线
 autocmd InsertEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"
 autocmd InsertLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"
 autocmd VimLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"
"支持鼠标
 set mouse=a
"显示行数
 set nu
"基本设置
 set encoding=utf-8
 set fileencoding=chinese
 set fileencodings=ucs-bom,utf-8,chinese
 set ambiwidth=double
 set ts=4
 set sw=4
 set wrap "自动换行
"设置无备份
 set nobackup
 set nowritebackup
